thisdict={"brand":"ford","model":"Nano","year":1964}
	  
print(thisdict)
print(type(thisdict))
print(len(thisdict))
print(thisdict.get("brand"))
print(thisdict["brand"])
print(thisdict["year"])
x=thisdict["model"]
print(x)
x=thisdict.keys()
print(x)
x=thisdict.values()
print(x)
print(thisdict.keys())
thisdict["colour"]="red"
print(thisdict)
thisdict["name"]="smm"
print(thisdict)